CREATE SEQUENCE  "SEQ_TR_CODIGO_AUTENTICACION"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE TR_CODIGO_AUTENTICACION (
    ID_CODIGO_AUTENTICACION                 NUMBER(10) NOT NULL,
    CODIGO_AUTENTICACION                    VARCHAR2(100 CHAR) NOT NULL,
    FK_ID_MEDIO_AUTENTICACION               NUMBER(10) NOT NULL,
    DESTINATARIO                            VARCHAR2(100 CHAR) NOT NULL,
    FECHA_CREACION_CODIGO_AUTENTICACION     DATE NOT NULL,
    CURP                                    VARCHAR2(18 CHAR) NOT NULL,
    FK_ID_ASESOR                          NUMBER(10) NOT NULL
);

COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.ID_CODIGO_AUTENTICACION IS
    'IDENTIFICADOR UNICO DE CODIGO DE AUTENTICACION';

COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.CODIGO_AUTENTICACION IS
    'CODIGO DE AUTENTICACION GENERADO ALEATORIAMENTE';

COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.FK_ID_MEDIO_AUTENTICACION IS
    'ID UNICO MEDIO AUTENTICACION RELACIONADPO CON TC MEDIO AUTENTICACION';

COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.DESTINATARIO IS
    'DESTINATARIO POR EL CUAL SE AUTENTICO EL PROSPECTO';

COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.FECHA_CREACION_CODIGO_AUTENTICACION IS
    'FECHA CREACION DEL CODIGO DE AUTENTICACION';
    
COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.CURP IS
    'CURP CON LA CUAL SE AUTENTICO EL PROSPECTO';
    
COMMENT ON COLUMN TR_CODIGO_AUTENTICACION.FK_ID_ASESOR IS
    'ID UNICO ASESOR RELACIONADPO CON TR ASESOR';

CREATE TABLE TC_MEDIO_AUTENTICACION (
    ID_MEDIO_AUTENTICACION                  NUMBER(10) NOT NULL,
    DESCRIPCION_MEDIO_AUTENTICACION         VARCHAR2(100 CHAR) NOT NULL,
    CLAVE                                   VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN TC_MEDIO_AUTENTICACION.ID_MEDIO_AUTENTICACION IS
    'IDENTIFICADOR UNICO DE MEDIO AUTENTICACION';

COMMENT ON COLUMN TC_MEDIO_AUTENTICACION.DESCRIPCION_MEDIO_AUTENTICACION IS
    'DESCRIPCION DEL MEDIO DE AUTENTICACION';

COMMENT ON COLUMN TC_MEDIO_AUTENTICACION.CLAVE IS
    'CLAVE DEL MEDIO AUTENTICACION';
    
ALTER TABLE TC_MEDIO_AUTENTICACION ADD CONSTRAINT TC_MEDIO_AUTENTICACION_PK PRIMARY KEY ( ID_MEDIO_AUTENTICACION );

ALTER TABLE TR_CODIGO_AUTENTICACION
    ADD CONSTRAINT TR_CODIGO_AUTEN_TC_MEDIO_AUTEN_FK FOREIGN KEY ( FK_ID_MEDIO_AUTENTICACION )
        REFERENCES TC_MEDIO_AUTENTICACION ( ID_MEDIO_AUTENTICACION );
        
ALTER TABLE TR_CODIGO_AUTENTICACION
    ADD CONSTRAINT TR_CODIGO_AUTEN_TR_ASESOR FOREIGN KEY ( FK_ID_ASESOR )
        REFERENCES TR_ASESOR ( ID_ASESOR );
        
INSERT INTO TC_MEDIO_AUTENTICACION VALUES (1,'SMS','01');
INSERT INTO TC_MEDIO_AUTENTICACION VALUES (2,'EMAIL','02');

COMMIT;